# Generated by Django 5.1.6 on 2025-02-21 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard', '0002_deck_last_accessed'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
