# Generated by Django 5.1.6 on 2025-02-21 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard', '0003_deck_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deck',
            name='theme',
            field=models.CharField(choices=[('default', 'Default'), ('sunrise', 'Sunrise'), ('tropical', 'Tropical'), ('ocean', 'Ocean'), ('lavender', 'Lavender')], default='default', max_length=20),
        ),
    ]
